---
- name: Download kubectl binary
  get_url:
    url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Verify kubectl version
  command: kubectl version --client
  register: kubectl_version
  changed_when: false

- debug:
    msg: "kubectl installed successfully - {{ kubectl_version.stdout }}"

